const express = require('express')
const router = express.Router()
const userRouter = require('./user')
const payosRouter = require('./payos')
const boardRouter = require('./board')
const listRouter = require('./list')
const cardRouter = require('./card')
const taskRouter = require('./task')
const activityRouter = require('./activity')
const workspaceRouter = require('./workspace')
const transactionRouter = require('./transaction')
const attachmentRouter = require('./attachment')
const statisticRouter = require('./statistic')
const messageRouter = require('./message')
const historyViewRouter = require('./historyview')
const verifyJWT = require('../../middlewares/verifyJWT')

router.use('/payos', payosRouter)
router.use(verifyJWT)
router.use('/history-view', historyViewRouter)
router.use('/boards', boardRouter)
router.use('/workspaces', workspaceRouter)
router.use('/acts', activityRouter)
router.use('/tasks', taskRouter)
router.use('/cards', cardRouter)
router.use('/lists', listRouter)
router.use('/users', userRouter)
router.use('/attachments', attachmentRouter)
router.use('/transactions', transactionRouter)
router.use('/statistics', statisticRouter)
router.use('/messages', messageRouter)


module.exports = router
